FROM ubuntu:24.04

# Update package lists and install stress-ng
RUN apt-get update && apt-get install -y stress-ng && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# CMD ["stress-ng", "--vm", "4", "--vm-bytes","1G","--vm-ops", "1000", "--metrics-brief"]